services:
  backend:
    container_name: pod_backend
    build: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./storage:/app/storage
      - ../pod.localhost/source/wp-content/uploads:/app/wp-uploads
    networks:
      - proxy_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pod_backend.rule=Host(`${APP_DOMAIN}`)"
      - "traefik.http.routers.pod_backend.entrypoints=web"
      - "traefik.http.services.pod_backend.loadbalancer.server.port=3001"
      - "traefik.docker.network=proxy_network"

networks:
  proxy_network:
    external: true
    name: proxy_network
