upload_max_filesize = 2048M
post_max_size = 2048M
memory_limit = 512M
max_execution_time = 600
max_input_time = 600

; Tắt OPcache trong môi trường Local Dev để code PHP cập nhật ngay lập tức (0s delay)
opcache.enable = 0
opcache.enable_cli = 0
opcache.revalidate_freq = 0

